language: python

python:
    - "3.4"
    - "3.5"

sudo: false

os:
    # Python builds are not available on the OSX environment.
    # see: https://docs.travis-ci.com/user/languages/python
    #- osx
    - linux

virtualenv:
    system_site_packages: false

before_install:
    # https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
    - pip install --upgrade pip
    - pip freeze
    - CHECKOUT_DIR=$(pwd)
    - echo ${CHECKOUT_DIR}
    - echo ${TRAVIS_BRANCH}
    - echo ${TRAVIS_COMMIT}
    - echo ${TRAVIS_REPO_SLUG}
    - echo ${GIT_TARGET_EXTRA}
    - echo ${GIT_SOURCE_EXTRA}
    - echo ${TRAVIS_PYTHON_VERSION}
    - git clone --depth 1 git://github.com/${TRAVIS_REPO_SLUG}.git ~/pyhardlinkbackup_clone

install:
    - cd ~/pyhardlinkbackup_clone
    - ls
    - ./boot_pyhardlinkbackup.sh
    - cd ~/PyHardLinkBackup
    - ls
    - pip uninstall -y PyHardLinkBackup
    - pip install -e git+https://github.com/jedie/PyHardLinkBackup.git#egg=pyhardlinkbackup
    - cd src/pyhardlinkbackup
    - git checkout -qf $TRAVIS_COMMIT
    - pip install -e .
    - pip freeze
    - MANAGE=$(which manage)
    - echo ${MANAGE}
    - ${MANAGE} migrate
    - cat requirements/dev_extras.txt
    - pip install -r requirements/dev_extras.txt

script:
    - which python
    - python --version
    - echo $(pwd)
    - NOSE_BIN=$(which nosetests)
    - echo ${NOSE_BIN}
    - coverage run --source=PyHardLinkBackup --parallel-mode ${NOSE_BIN}
    - coverage combine

after_success: coveralls

notifications:
    irc: "irc.freenode.org#pylucid"
