# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/environment-variables

version: "{build}"

# blacklist
#except:
#  - gh-pages

build: false

environment:
    matrix:
      # 'scandir' will not installed on python 2.4 via setup, yet:
      # https://www.python-forum.de/viewtopic.php?f=2&t=37802&p=289841#p289841
#      - PYTHON: "C:\\Python34"
#        PY_PYTHON: 3.4-32
#        PY_PYTHON3: 3.4-32
#        PYTHON_VERSION: "3.4.x"
#        PYTHON_ARCH: "32"
#
#      - PYTHON: "C:\\Python34-x64"
#        PY_PYTHON: 3.4
#        PY_PYTHON3: 3.4
#        PYTHON_VERSION: "3.4.x"
#        PYTHON_ARCH: "64"

      # Python 3.5-32 won't run through the C:\Windows\py.exe launcher on
      # AppVeyor for some reason. See:
      # http://help.appveyor.com/discussions/problems/3891-py-35-32-hellopy-fails-with-error-code-103
      # - PYTHON: "C:\\Python35"
      # - PY_PYTHON: 3.5-32
      # - PY_PYTHON3: 3.5-32
      # - PYTHON_VERSION: "3.5.x"
      # - PYTHON_ARCH: "32"

      - PYTHON: "C:\\Python35-x64"
        PY_PYTHON: 3.5
        PY_PYTHON3: 3.5
        PYTHON_VERSION: "3.5.x"
        PYTHON_ARCH: "64"

platform:
    - AnyCPU

init:
    - echo %PYTHON%
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    - set

    # Check that we have the expected version and architecture for Python
    - "python --version"
    - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
    - "py -V"
    - "py -c \"import sys; print(sys.version)\""
    - "py -3 -V"
    - "py -3 -c \"import sys; print(sys.version)\""

# clone directory
clone_folder: c:/pyhardlinkbackup_clone

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

install:
    - cd c:/pyhardlinkbackup_clone
    - "py -3 -c \"from dev.patch_cmd import patch;patch('boot_pyhardlinkbackup.cmd', debug=False)\""
    - boot_pyhardlinkbackup.cmd
    - cd %APPDATA%/PyHardLinkBackup/Scripts
    - pip uninstall -y PyHardLinkBackup
    - pip install -e git+https://github.com/jedie/PyHardLinkBackup.git#egg=pyhardlinkbackup
    - cd %APPDATA%/PyHardLinkBackup/src/pyhardlinkbackup
    - git checkout -qf %APPVEYOR_REPO_COMMIT%
    - pip install -e .
    - pip install -r requirements/dev_extras.txt
    - manage migrate

test_script:
    - cd %APPDATA%/PyHardLinkBackup/src/pyhardlinkbackup
    - coverage run --source=PyHardLinkBackup --parallel-mode %APPDATA%/PyHardLinkBackup/Scripts/nosetests
    - coverage combine
    - coveralls
